### ISSUE TITLE
2.7.* is not a valid version of puppet

### ISSUE THREAD

**Issue by jaffacake** [petems/vagrant-puppet-install#23]
I've just started using your plugin and it worked great when enter 2.7.26, however I want it to get the latest minor release, however adding 2.7.* states that it is not a valid version. Shouldn't this work?

**Comment by christopher-hopper** [comment]
@jaffacake according to the documentation in the README.md '2.7.*' should work, but I have also found it does not. Perhaps we should just adjust the README to prevent confusion.

**Comment by petems** [comment]
Need to update the README, the version validation just uses the Rubygems API to check versions.

So using the Ruby syntax of "~> 2.7" would be how to fix this.

**Comment by petems** [comment]
Clarified in #24
