### ISSUE TITLE
The package is just called puppet-agent

### ISSUE THREAD

**Issue by jacobsevart** [petems/vagrant-puppet-install#31]
This fails for me with Vagrant 1.8.1 on OSX with the 'debian/jessie64' box because it attempts to install the package named puppet-agent-1.3.2, which is wrong. It should just be puppet-agent.

Output at https://gist.github.com/jacobsevart/660b60f87f6795e8a2a1

**Comment by petems** [comment]
Indeed, that should be puppet-agent=1.3.2 on Debian...

**Comment by petems** [comment]
Fixed in https://github.com/petems/puppet-install-shell/commit/e22d88c099175079bacde62e9d37da2132d0666a
