### ISSUE TITLE
"offline" mode?

### ISSUE THREAD

**Issue by glenjamin** [petems/vagrant-puppet-install#37]
I quite often work on a train with poor internet connections - usually making small changes to something that mostly already works.

This plugin always attempts to validate the puppet version against the rubygems API - which requires quite a lot of data transfer over the network.

Would you be open to providing a way to disable this check? Perhaps skipping it entirely if the puppet version is already fully qualified?

**Comment by petems** [comment]
Yep, this should be configurable. Just an option to disable the version validation check.

**Comment by glenjamin** [comment]
Awesome, thanks!

**Comment by petems** [comment]
This is now released in version `4.1.0` 👍
