### ISSUE TITLE
Please document the config.puppet_install.install_url parameter

### ISSUE THREAD

**Issue by robinbowes** [petems/vagrant-puppet-install#53]
It was only through looking in the source code that I noticed I could specify a custom url from which to grab the puppet install script - useful if it needs updating for new puppet releases and you haven't yet updated.

Can you maybe put a section in the README that documents this and possibly other config options?

R.

**Comment by petems** [comment]
It's in the readme: 

```
Specify a custom install script:

Vagrant.configure("2") do |config|

  config.puppet_install.install_url = 'http://acme.com/install.sh'
  # config.puppet_install.install_url = 'http://acme.com/install.msi'
  # config.puppet_install.install_url = '/some/path/on/the/host'

  ...

end
```

**Comment by robinbowes** [comment]
Dang, I missed that. :)
