### ISSUE TITLE
Issues with Ubuntu 17.10?

### ISSUE THREAD

**Issue by Snaver** [petems/vagrant-puppet-install#60]
==> default: Installing Puppet 5.3.3 package...
==> default: 10:17:06 +0000 INFO: Version parameter defined: 5.3.3
==> default: 10:17:06 +0000 INFO: Downloading Puppet 5.3.3 for ubuntu...
==> default: 10:17:06 +0000 INFO: Ubuntu platform! Lets get you a DEB...
==> default: 10:17:06 +0000 INFO: Downloading http://apt.puppetlabs.com/puppet5-release-.deb
==> default: 10:17:06 +0000 INFO:   to file /tmp/install.sh.1242.random_hexdump/puppet5-release-.deb
==> default: 10:17:06 +0000 INFO: Trying wget...
==> default: 10:17:07 +0000 CRIT: ERROR 404
==> default: 10:17:07 +0000 CRIT: Unable to retrieve a valid package!
==> default: 10:17:07 +0000 CRIT: Please file a bug report at https://github.com/petems/puppet-install-shell/
==> default: 10:17:07 +0000 CRIT:
==> default: 10:17:07 +0000 CRIT: Version: 5.3.3
==> default: 10:17:07 +0000 CRIT: Platform: ubuntu
==> default: 10:17:07 +0000 CRIT: Platform Version: 17.10
==> default: 10:17:07 +0000 CRIT: Machine: x86_64
==> default: 10:17:07 +0000 CRIT: OS: Linux
==> default: 10:17:07 +0000 CRIT:
==> default: 10:17:07 +0000 CRIT: Please detail your operating system type, version and any other relevant details
The following SSH command responded with a non-zero exit status.

**Comment by petems** [comment]
17.10 is now EOL, closing
